// -----------------------------------------------------------------------------------------
// Copyright © 2026 OzzieAI - Chris Sykes. All rights reserved.
// 
// Project:      ArborNet
// Description:  A C# Machine Learning Library implemented in .NET 10 with full CUDA support.
// 
// License:      MIT License
// -----------------------------------------------------------------------------------------

namespace MSBuildTask
{

    #region Using Statements:

    using Microsoft.Build.Framework;
    using Microsoft.Build.Utilities;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using RequiredAttribute = Microsoft.Build.Framework.RequiredAttribute;
    using Task = Microsoft.Build.Utilities.Task;
    /// <summary>
    /// A custom MSBuild task that compiles CUDA source files (.cu) into Parallel Thread Execution (.ptx) files 
    /// or shared libraries using the NVIDIA CUDA Compiler (nvcc), and generates corresponding C# wrapper files.
    /// </summary>
    /// <remarks>
    /// This task orchestrates the compilation of CUDA kernels directly within the MSBuild lifecycle.
    /// It intercepts specified .cu source files, runs the external nvcc compiler with specified architecture parameters,
    /// redirects standard output and error streams to the MSBuild logger, and registers outputs for downstream compilation targets.
    /// </remarks>

    #endregion

    public class CudaCompileTask : Task
    {
        /// <summary>
        /// Gets or sets the list of CUDA source files (.cu) to compile. 
        /// </summary>
        /// <value>
        /// An array of <see cref="ITaskItem"/> instances specifying paths to the .cu source files.
        /// </value>
        /// <remarks>
        /// This is a mandatory input parameter. Due to the <see cref="RequiredAttribute"/>, 
        /// MSBuild will halt execution and log an error if this property is not provided.
        /// </remarks>

        [Required]
        public ITaskItem[] CudaFiles { get; set; }
        /// <summary>
        /// Gets or sets the resulting PTX or binary files generated by the NVIDIA CUDA Compiler (nvcc).
        /// </summary>
        /// <value>
        /// An array of <see cref="ITaskItem"/> instances pointing to the successfully generated output files.
        /// </value>
        /// <remarks>
        /// This is an output parameter. It can be consumed by subsequent tasks in the build pipeline,
        /// such as embedding them as resources or copying them to the project build output folder.
        /// </remarks>

        [Output]
        public ITaskItem[] GeneratedPtxFiles { get; set; }
        /// <summary>
        /// Gets or sets the generated C# wrapper files corresponding to the compiled CUDA source files.
        /// </summary>
        /// <value>
        /// An array of <see cref="ITaskItem"/> instances pointing to the auto-generated code-behind (.g.cs) files.
        /// </value>
        /// <remarks>
        /// This is an output parameter. It provides the paths of generated wrapper classes, allowing them
        /// to be dynamically compiled with the host application.
        /// </remarks>

        [Output]
        public ITaskItem[] GeneratedCsFiles { get; set; }
        /// <summary>
        /// Executes the CUDA compilation task by invoking the nvcc compiler.
        /// </summary>
        /// <returns>
        /// <see langword="true"/> if the compilation completes successfully and no errors are logged; otherwise, <see langword="false"/>.
        /// </returns>
        /// <remarks>
        /// This method processes each file in <see cref="CudaFiles"/> sequentially. 
        /// It invokes <c>nvcc</c> to compile all source files into a shared library, redirects standard output 
        /// and error streams to the build engine logger, and generates C# wrapper templates on disk.
        /// </remarks>
        /// <exception cref="System.IO.IOException">Thrown if the generated wrapper files cannot be written to disk.</exception>
        /// <exception cref="System.UnauthorizedAccessException">Thrown if permissions prevent writing to the output directory.</exception>

        public override bool Execute()
        {
            var ptxItems = new List<ITaskItem>();
            var csItems = new List<ITaskItem>();

            if (CudaFiles == null || CudaFiles.Length == 0) return true;

            // Concatenate all source files into a single input sequence for nvcc
            string allSources = string.Join(" ", CudaFiles.Select(f => $"\"{f.ItemSpec}\""));

            Log.LogMessage(MessageImportance.High, "Compiling all CUDA source files into cuda_backend.dll...");

            var psi = new ProcessStartInfo("nvcc")
            {
                Arguments = $"--shared {allSources} -o \"cuda_backend.dll\" --gpu-architecture=sm_80 -lcudart",
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true
            };

            using (var process = Process.Start(psi))
            {
                if (process == null)
                {
                    Log.LogError("Failed to start nvcc. Ensure CUDA Toolkit is in your PATH.");
                    return false;
                }

                process.OutputDataReceived += (sender, args) => { if (args.Data != null) Log.LogMessage(MessageImportance.Normal, args.Data); };
                process.ErrorDataReceived += (sender, args) => { if (args.Data != null) Log.LogError(args.Data); };

                process.BeginOutputReadLine();
                process.BeginErrorReadLine();
                process.WaitForExit();

                if (process.ExitCode != 0)
                {
                    Log.LogError($"nvcc compilation failed with exit code {process.ExitCode}");
                    return false;
                }
            }

            // Register all compiled files
            foreach (var cu in CudaFiles)
            {
                string ptxPath = Path.ChangeExtension(cu.ItemSpec, ".ptx");
                string csPath = Path.ChangeExtension(cu.ItemSpec, ".g.cs");

                File.WriteAllText(csPath, $"// Auto-generated wrapper for {Path.GetFileName(cu.ItemSpec)}\n");
                ptxItems.Add(new TaskItem(ptxPath));
                csItems.Add(new TaskItem(csPath));
            }

            GeneratedPtxFiles = ptxItems.ToArray();
            GeneratedCsFiles = csItems.ToArray();
            return !Log.HasLoggedErrors;
        }
    }
}