using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using RequiredAttribute = Microsoft.Build.Framework.RequiredAttribute;
using Task = Microsoft.Build.Utilities.Task;

namespace MSBuildTask
{
    /// <summary>
    /// A custom MSBuild task that compiles CUDA source files (.cu) into Parallel Thread Execution (.ptx) files 
    /// using the NVIDIA CUDA Compiler (nvcc), and generates corresponding C# wrapper files.
    /// </summary>
    public class CudaCompileTask : Task
    {
    
        /// <summary>
        /// Gets or sets the list of CUDA source files to compile. 
        /// This is a mandatory input for the task to run.
        /// </summary>
        /// <value>An array of <see cref="ITaskItem"/> instances specifying paths to .cu source files.</value>
        /// <remarks>
        /// This property must be supplied by the MSBuild project file. Due to the <see cref="RequiredAttribute"/>,
        /// MSBuild will report an error and skip the task if this input is empty or null.
        /// </remarks>
        [Required]
        public ITaskItem[] CudaFiles { get; set; }

        /// <summary>
        /// Gets or sets the resulting PTX files generated by nvcc.
        /// MSBuild can use this output to embed the PTX files as resources or copy them to the output directory.
        /// </summary>
        /// <value>An array of <see cref="ITaskItem"/> instances pointing to the generated .ptx output files.</value>
        /// <remarks>
        /// Only successfully compiled files contribute to this output. These items can be consumed by subsequent
        /// MSBuild targets, such as <c>&lt;EmbededResource&gt;</c> or <c>&lt;Copy&gt;</c>.
        /// </remarks>
        [Output]
        public ITaskItem[] GeneratedPtxFiles { get; set; }

        /// <summary>
        /// Gets or sets the generated C# wrapper files.
        /// MSBuild can pipe this output directly into the C# compiler's source file list.
        /// </summary>
        /// <value>An array of <see cref="ITaskItem"/> instances pointing to the generated .g.cs wrapper files.</value>
        /// <remarks>
        /// These wrapper files are auto-generated placeholders and can be processed by <c>&lt;Csc&gt;</c> targets.
        /// Only successfully compiled files produce corresponding wrappers.
        /// </remarks>
        [Output]
        public ITaskItem[] GeneratedCsFiles { get; set; }

        /// <summary>
        /// Executes the task. Intercepts each .cu file, shells out to nvcc, captures the output, 
        /// and registers the generated files back to the MSBuild engine.
        /// </summary>
        /// <returns>True if all files compiled successfully; False if any errors were logged.</returns>
        /// <remarks>
        /// This task processes every input file sequentially, logging progress, warnings, and errors from nvcc
        /// directly into MSBuild's logging system for integration with Visual Studio's Error List.
        /// Compilation continues for all files even if some fail, maximizing error reporting.
        /// The task uses <c>nvcc --shared</c> targeting <c>sm_80</c> (Ampere architecture) and links <c>libcudart</c>.
        /// PTX output paths are registered, with corresponding C# wrappers generated as placeholders.
        /// Overall success depends on <see cref="TaskLoggingHelper.HasLoggedErrors"/>.
        /// </remarks>
        public override bool Execute()
        {
            /// <summary>
            /// Collection of ITaskItem instances for successfully generated PTX files.
            /// Populated only for compilations with exit code 0 and assigned to <see cref="GeneratedPtxFiles"/>.
            /// </summary>
            var ptxItems = new List<ITaskItem>();
            /// <summary>
            /// Collection of ITaskItem instances for generated C# wrapper files.
            /// Populated only for successful compilations and assigned to <see cref="GeneratedCsFiles"/>.
            /// </summary>
            var csItems = new List<ITaskItem>();

            foreach (var cu in CudaFiles)
            {
                /// <summary>
                /// Absolute path to the current .cu source file, obtained from ITaskItem.ItemSpec.
                /// </summary>
                string sourcePath = cu.ItemSpec;
                /// <summary>
                /// Computed output path for the PTX file by replacing .cu extension with .ptx.
                /// Used to register output items regardless of actual nvcc output location.
                /// </summary>
                string ptxPath = Path.ChangeExtension(sourcePath, ".ptx");

                // Broadcast progress to the Visual Studio Output window
                Log.LogMessage(MessageImportance.High, $"Compiling {sourcePath} to PTX...");

                // Configure the nvcc compiler process
                /// <summary>
                /// ProcessStartInfo configured to invoke nvcc.exe with redirected I/O for logging integration.
                /// Arguments produce a shared library DLL targeting SM 8.0, overwriting "cuda_backend.dll".
                /// </summary>
                var psi = new ProcessStartInfo("nvcc")
                {
                    // Target SM_80 architecture (Ampere GPUs like A100/RTX 30-series)
                    // Quotes ensure paths with spaces do not break the command
                    // Arguments = $"-ptx \"{sourcePath}\" -o \"{ptxPath}\" --gpu-architecture=sm_80",
                    // Change -ptx to --shared to create a DLL instead of assembly text
                    Arguments = $"--shared \"{sourcePath}\" -o \"cuda_backend.dll\" --gpu-architecture=sm_80 -lcudart",
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    CreateNoWindow = true
                };

                using (var process = Process.Start(psi))
                {
                    if (process == null)
                    {
                        Log.LogError("Failed to start nvcc. Ensure the CUDA toolkit is installed and in your PATH.");
                        return false; // Abort early if the compiler is missing
                    }

                    // Wire up the compiler's output streams directly into MSBuild's logging system
                    // This ensures nvcc warnings/errors appear natively in the Visual Studio Error List
                    /// <summary>
                    /// Event handler that forwards nvcc standard output lines to MSBuild message logs.
                    /// Filters out empty lines for cleaner output.
                    /// </summary>
                    /// <param name="sender">The <see cref="Process"/> instance raising the event.</param>
                    /// <param name="args"><see cref="DataReceivedEventArgs"/> containing the output line in <see cref="DataReceivedEventArgs.Data"/>.</param>
                    process.OutputDataReceived += (sender, args) =>
                    {
                        if (!string.IsNullOrWhiteSpace(args.Data))
                            Log.LogMessage(MessageImportance.Normal, args.Data);
                    };

                    /// <summary>
                    /// Event handler that forwards nvcc standard error lines to MSBuild error logs.
                    /// Filters out empty lines; contributes to <see cref="TaskLoggingHelper.HasLoggedErrors"/>.
                    /// </summary>
                    /// <param name="sender">The <see cref="Process"/> instance raising the event.</param>
                    /// <param name="args"><see cref="DataReceivedEventArgs"/> containing the error line in <see cref="DataReceivedEventArgs.Data"/>.</param>
                    process.ErrorDataReceived += (sender, args) =>
                    {
                        if (!string.IsNullOrWhiteSpace(args.Data))
                            Log.LogError(args.Data);
                    };

                    // Begin listening to the streams
                    process.BeginOutputReadLine();
                    process.BeginErrorReadLine();

                    // Block MSBuild from finishing the task until the compiler is done
                    process.WaitForExit();

                    // Evaluate the result
                    if (process.ExitCode != 0)
                    {
                        Log.LogError($"nvcc compilation failed with exit code {process.ExitCode} for {sourcePath}");
                        // Note: We intentionally do not 'return false' here so the loop continues 
                        // and reveals errors in *all* files, rather than failing on the first one.
                    }
                    else
                    {
                        // 1. Record the successful PTX generation as a new MSBuild item
                        ptxItems.Add(new TaskItem(ptxPath));

                        // 2. Generate the C# wrapper script
                        /// <summary>
                        /// Computed path for the auto-generated C# wrapper file (.g.cs).
                        /// Contains placeholder content for future P/Invoke or kernel launch logic.
                        /// </summary>
                        string csPath = Path.ChangeExtension(sourcePath, ".g.cs");
                        File.WriteAllText(csPath, $"// Auto-generated wrapper for {Path.GetFileName(sourcePath)}\n// Add your generator logic here.");

                        // Record the generated C# file as a new MSBuild item
                        csItems.Add(new TaskItem(csPath));
                    }
                }
            }

            // Assign our populated lists back to the [Output] properties
            GeneratedPtxFiles = ptxItems.ToArray();
            GeneratedCsFiles = csItems.ToArray();

            // MSBuild determines task success based on whether any Log.LogError() calls were made
            return !Log.HasLoggedErrors;
        }
    }
}