// -----------------------------------------------------------------------------------------
// Copyright © 2026 OzzieAI - Chris Sykes. All rights reserved.
// 
// Project:      ArborNet
// Description:  A C# Machine Learning Library implemented in .NET 10 with full CUDA support.
// 
// License:      MIT License
// -----------------------------------------------------------------------------------------

namespace ArborNet.Core.Interfaces
{

    #region Using Statements:

    using System;
    using ArborNet.Core.Devices;
    using ArborNet.Core.Tensors;
    /// <summary>
    /// Provides an abstract base implementation for all loss (cost) functions within the ArborNet framework.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Loss functions evaluate the discrepancy between the predictions generated by a machine learning model
    /// and the actual ground-truth targets. This base class encapsulates standard utilities shared across
    /// various loss implementations, such as input shape validation and reduction post-processing.
    /// </para>
    /// <para>
    /// Concrete classes deriving from <see cref="BaseLoss"/> must implement the <see cref="Forward"/> method
    /// to define the specific mathematical formulation of the loss (e.g., Mean Squared Error, Cross-Entropy).
    /// </para>
    /// </remarks>

    #endregion

    public abstract class BaseLoss : ILoss
    {
        /// <summary>
        /// Computes the loss value between the model's predicted outputs and the target ground-truth values.
        /// </summary>
        /// <param name="predictions">The predicted <see cref="ITensor"/> outputted by the model. Must not be null and must match the shape of <paramref name="targets"/>.</param>
        /// <param name="targets">The ground-truth target <see cref="ITensor"/>. Must not be null and must match the shape of <paramref name="predictions"/>.</param>
        /// <param name="reduction">The reduction method to apply to the calculated loss. Supported values are:
        /// <list type="bullet">
        /// <item><description><c>"mean"</c> (default) - Computes the average of all element-wise losses.</description></item>
        /// <item><description><c>"sum"</c> - Computes the sum of all element-wise losses.</description></item>
        /// <item><description><c>"none"</c> - Returns the element-wise losses without reduction, matching the shape of the inputs.</description></item>
        /// </list>
        /// </param>
        /// <returns>An <see cref="ITensor"/> representing the reduced loss value(s).</returns>
        /// <exception cref="ArgumentNullException">Thrown if either <paramref name="predictions"/> or <paramref name="targets"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentException">Thrown if the shapes of <paramref name="predictions"/> and <paramref name="targets"/> are not identical.</exception>
        public abstract ITensor Forward(ITensor predictions, ITensor targets, string reduction = "mean");
        /// <summary>
        /// Validates that the prediction and target tensors are non-null and have matching shapes.
        /// </summary>
        /// <param name="predictions">The predictions <see cref="ITensor"/> to validate.</param>
        /// <param name="targets">The targets <see cref="ITensor"/> to validate.</param>
        /// <exception cref="ArgumentNullException">
        /// Thrown when <paramref name="predictions"/> or <paramref name="targets"/> is <see langword="null"/>.
        /// </exception>
        /// <exception cref="ArgumentException">
        /// Thrown when the dimensions or shape of <paramref name="predictions"/> do not match <paramref name="targets"/>.
        /// </exception>

        protected void ValidateInputs(ITensor predictions, ITensor targets)
        {
            if (predictions == null) throw new ArgumentNullException(nameof(predictions));
            if (targets == null) throw new ArgumentNullException(nameof(targets));
            if (!predictions.Shape.Equals(targets.Shape))
                throw new ArgumentException("Predictions and targets must have identical shapes.");
        }
        /// <summary>
        /// Reduces the computed loss tensor based on the specified reduction strategy.
        /// </summary>
        /// <param name="loss">The raw, unreduced loss tensor containing element-wise losses.</param>
        /// <param name="reduction">The reduction mode to apply. Can be <c>"sum"</c>, <c>"none"</c>, or any other value (which defaults to <c>"mean"</c>).</param>
        /// <param name="originalShapeTensor">An optional tensor containing shape reference information, useful for custom reduction implementations.</param>
        /// <returns>A new <see cref="ITensor"/> that has been reduced to a scalar or a lower-dimensional tensor depending on the <paramref name="reduction"/> mode.</returns>
        /// <remarks>
        /// Supported reduction algorithms:
        /// <list type="table">
        /// <listheader>
        /// <term>Strategy</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>sum</term>
        /// <description>Sums all elements in the tensor, yielding a 0-dimensional scalar tensor.</description>
        /// </item>
        /// <item>
        /// <term>none</term>
        /// <description>Returns the input <paramref name="loss"/> tensor unmodified.</description>
        /// </item>
        /// <item>
        /// <term>mean (or any other value)</term>
        /// <description>Computes the arithmetic mean over all elements, yielding a 0-dimensional scalar tensor.</description>
        /// </item>
        /// </list>
        /// </remarks>

        protected ITensor ApplyReduction(ITensor loss, string reduction, ITensor originalShapeTensor)
        {
            return reduction.ToLowerInvariant() switch
            {
                "sum" => loss.Sum(),
                "none" => loss,
                _ => loss.Mean()
            };
        }
    }
}