<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Native\Cuda Libs\**" />
    <EmbeddedResource Remove="Native\Cuda Libs\**" />
    <None Remove="Native\Cuda Libs\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Native\Kernels\" />
  </ItemGroup>

</Project>