// -----------------------------------------------------------------------------------------
// Copyright © 2026 OzzieAI - Chris Sykes. All rights reserved.
// 
// Project:      ArborNet
// Description:  A C# Machine Learning Library implemented in .NET 10 with full CUDA support.
// 
// License:      MIT License
// -----------------------------------------------------------------------------------------

namespace ArborNet.Core
{



    #region
    #endregion


    /// <summary>
    /// Specifies the mathematical fractal generation algorithms and visualization patterns 
    /// supported by the ArborNet Core framework.
    /// </summary>
    /// <remarks>
    /// This enumeration is used by the rendering engine to select the appropriate mathematical 
    /// generator and apply corresponding geometric transformations, coordinate mapping, and color-ramp algorithms.
    /// </remarks>
    public enum FractalType
    {
        /// <summary>
        /// A fractal visualization generated from the patterns and intervals (gaps) between successive prime numbers.
        /// </summary>
        /// <remarks>
        /// Maps the prime gap differences to spatial coordinates or polar vectors, resulting in a deterministic yet 
        /// highly irregular geometric structure that highlights the underlying distribution of prime numbers.
        /// </remarks>
        PrimeGapSignature,

        /// <summary>
        /// A complex visualization mapping the boundary conditions of the Mandelbrot set overlaid with chaotic bifurcation transitions.
        /// </summary>
        /// <remarks>
        /// Integrates the classic quadratic recurrence formula with the logistic map's bifurcation values, 
        /// visualizing the boundary areas where mathematical stability transitions into chaotic behavior.
        /// </remarks>
        MandelbrotBifurcation,

        /// <summary>
        /// An iterative, multi-dimensional Cantor set representation generated by repeatedly partitioning and removing spatial segments.
        /// </summary>
        /// <remarks>
        /// Represents a multi-dimensional generalization of the Cantor ternary set. This algorithm repeatedly subtracts 
        /// central regions from a given space, producing a dust-like fractal pattern with a non-integer Hausdorff dimension.
        /// </remarks>
        CantorDustSieve,

        /// <summary>
        /// A phase-space spiral fractal governed by the golden ratio (phi) constant, exhibiting logarithmic scaling characteristics.
        /// </summary>
        /// <remarks>
        /// Employs the golden ratio constant to define progressive rotation angles and scaling coefficients, 
        /// constructing highly optimized, self-similar logarithmic spirals akin to phyllotaxis patterns in nature.
        /// </remarks>
        GoldenRatioPhase,

        /// <summary>
        /// A directed tree or vector field fractal mapped from the iterative trajectory paths of the Collatz (3n + 1) conjecture.
        /// </summary>
        /// <remarks>
        /// Traces the convergence pathways of integers under the Collatz function. The trajectories are rendered 
        /// as directed vector branches, creating organic, tree-like structures.
        /// </remarks>
        CollatzSequence
    }
}